### ISSUE TITLE
Addition fields not working!!

### ISSUE THREAD

**Issue by michael-jakobsen-dk** [RallyCommunity/portfolio-item-copy#13]
I cannot get the app to work. Only the main fields are being copied, but not even PlanEstimate on user stories + none of the additionally selected fields are copied.

**Comment by michael-jakobsen-dk** [comment]
The problem is in the launch method. The app.fieldsToCopy is not populated correctly - maybe an issue with javascript array/object...

**Comment by michael-jakobsen-dk** [comment]
Bug fixed:

Line 106:
Ext.apply(app.fieldsToCopy, requiredFields);

Doesn't merge the two objects, but overwrite the content in app.fieldsToCopy, because the same name pairs exists in requiredFields.

Replace with:
app.fieldsToCopy.portfolioitem = Ext.Array.unique(app.fieldsToCopy.portfolioitem.concat(requiredFields.portfolioitem));
                app.fieldsToCopy.hierarchicalrequirement = Ext.Array.unique(app.fieldsToCopy.hierarchicalrequirement.concat(requiredFields.hierarchicalrequirement));
                app.fieldsToCopy.task = Ext.Array.unique(app.fieldsToCopy.task.concat(requiredFields.task));

Or similar code that does the same - I'm not a javascript expert.

**Comment by krmorse** [comment]
@michael-jakobsen-dk thanks for reporting this and for supplying the fix!  I think i have this taken care of if you'd like to test it in custom html format: https://raw.githubusercontent.com/RallyCommunity/portfolio-item-copy/39d5706381679f29f32e5d74046b76f5fb6df653/deploy/App-uncompressed.html

If that looks good to you then I'll get it merged and promoted into the community app catalog on rally1.

**Comment by krmorse** [comment]
Fixed in v1.0.2
