### ISSUE TITLE
App does not support renaming of lowest level portfolio item

### ISSUE THREAD

**Issue by michael-jakobsen-dk** [RallyCommunity/portfolio-item-copy#14]
The lowest level portfolio item must be named Feature to be able to choose fields in the app settings.

app.js lines 454+456 must be changed if you have chosen another name than Feature.

**Comment by krmorse** [comment]
@michael-jakobsen-dk thanks for reporting this and for supplying the fix!  I think i have this taken care of if you'd like to test it in custom html format: https://raw.githubusercontent.com/RallyCommunity/portfolio-item-copy/39d5706381679f29f32e5d74046b76f5fb6df653/deploy/App-uncompressed.html

If that looks good to you then I'll get it merged and promoted into the community app catalog on rally1.

**Comment by krmorse** [comment]
Fixed in v1.0.2
