### ISSUE TITLE
User stories ranks change

### ISSUE THREAD

**Issue by nadek** [RallyCommunity/portfolio-item-copy#4]
When a portfolio item is copied using the portfolio item copy, the ranks of the user stories are different in the newly created portfolio item.

**Comment by krmorse** [comment]
@michael-jakobsen-dk, @nadek would it make sense to always preserve order, or would you want an app setting to control that feature?  There are some performance considerations to be made (preserving rank will be a little slower)

Anyway, there is already some code written to do this.  I'd like to merge the other outstanding pr first (#15) and then maybe we can work on getting this resolved.

**Comment by krmorse** [comment]
@nadek @michael-jakobsen-dk, it actually ended up being fairly easy to bring in the changes to fix the ordering of children.  if you'd like to test out all the fixes you can do so here: https://raw.githubusercontent.com/RallyCommunity/portfolio-item-copy/a8a5c46f1f9e48162d3c140c37ecec97f36f32c2/deploy/App-uncompressed.html

if it seems like that all works let me know and i'll get this all merged and promoted to the community catalog on rally1.

**Comment by krmorse** [comment]
Fixed in v1.0.2
