### ISSUE TITLE
Task Estimate/Plan Estimate Values not copying over

### ISSUE THREAD

**Issue by AJ56321** [RallyCommunity/portfolio-item-copy#9]
These values had been getting copied in the past but it looks like all values now get zeroed out after the copy.

**Comment by krmorse** [comment]
@AJ56321 thanks for reporting this.  I think i have this taken care of if you'd like to test it in custom html format: https://raw.githubusercontent.com/RallyCommunity/portfolio-item-copy/39d5706381679f29f32e5d74046b76f5fb6df653/deploy/App-uncompressed.html

If that looks good to you then I'll get it merged and promoted into the community app catalog on rally1.

**Comment by AJ56321** [comment]
Looks good to me. Thanks!

**Comment by krmorse** [comment]
Fixed in v1.0.2
